COMMON_PHRASES = [
    "A bird in the hand is worth two in the bush.",
    "A penny for your thoughts.",
    "A penny saved is a penny earned.",
    "A picture is worth 1000 words.",
    "Actions speak louder than words.",
    "Barking up the wrong tree.",
    "Birds of a feather flock together.",
    "By the skin of your teeth.",
    "Comparing apples to oranges.",
    "Do unto others as you would have them do unto you.",
    "Don't count your chickens before they hatch.",
    "Don't cry over spilt milk.",
    "Don't give up your day job.",
    "Don't put all your eggs in one basket.",
    "Every cloud has a silver lining.",
    "Get a taste of your own medicine.",
    "Good things come to those who wait.",
    "He has bigger fish to fry.",
    "He's a chip off the old block.",
    "Hit the nail on the head.",
    "It ain't over till the fat lady sings.",
    "It takes one to know one.",
    "It's raining cats and dogs.",
    "Kill two birds with one stone.",
    "Let the cat out of the bag.",
    "Look before you leap.",
    "Saving for a rainy day.",
    "Slow and steady wins the race.",
    "Take it with a grain of salt.",
    "The ball is in your court.",
    "The best thing since sliced bread.",
    "The devil is in the details.",
    "The early bird gets the worm.",
    "The elephant in the room.",
    "The whole nine yards.",
    "There are other fish in the sea.",
    "There's a method to his madness.",
    "There's no such thing as a free lunch.",
    "Throw caution to the wind.",
    "You can't have your cake and eat it too.",
    "You can't judge a book by its cover.",
    "A little learning is a dangerous thing.",
    "A snowball's chance in hell.",
    "A stitch in time saves nine.",
    "An apple a day keeps the doctor away.",
    "An ounce of prevention is worth a pound of cure.",
    "Bolt from the blue.",
    "Calm before the storm.",
    "Curiosity killed the cat.",
    "Don't beat a dead horse.",
    "Every dog has his day.",
    "Familiarity breeds contempt.",
    "Fortune favours the bold.",
    "Haste makes waste.",
    "He who laughs last laughs loudest.",
    "He's not playing with a full deck.",
    "He's sitting on the fence.",
    "It is a poor workman who blames his tools.",
    "It is always darkest before the dawn.",
    "It takes two to tango.",
    "Know which way the wind is blowing.",
    "Leave no stone unturned.",
    "Let sleeping dogs lie.",
    "Like riding a bicycle.",
    "Like two peas in a pod.",
    "Make hay while the sun shines.",
    "Once bitten, twice shy.",
    "Out of the frying pan and into the fire.",
    "Shape up or ship out.",
    "The pot calling the kettle black.",
    "There are clouds on the horizon.",
    "Those who live in glass houses shouldn't throw stones.",
    "Through thick and thin.",
    "Waste not, want not.",
    "Well begun is half done.",
    "When it rains it pours.",
    "You can't make an omelet without breaking some eggs.",
]

NOVEL_EXCERPTS = [
    "The Ministry of Truth, which concerned itself with news, entertainment, education and the fine arts. The Ministry of Peace, which concerned itself with war. The Ministry of Love, which maintained law and order. And the Ministry of Plenty, which was responsible for economic affairs. Their names, in Newspeak: Minitrue, Minipax, Miniluv and Miniplenty.",
    "He found himself understanding the wearisomeness of this life, where every path was an improvisation and a considerable part of one's waking life was spent watching one's feet.",
    "Vonnegut could not help looking back, despite the danger of being turned metaphorically into a pillar of salt, into an emblem of the death that comes to those who cannot let go of the past.",
    "But I remembered one thing: it wasn't me that started acting deaf; it was people that first started acting like I was too dumb to hear or see or say anything at all.",
    "When today fails to offer the justification for hope, tomorrow becomes the only grail worth pursuing.",
    "It is far better to endure patiently a smart which nobody feels but yourself, than to commit a hasty action whose evil consequences will extend to all connected with you; and besides, the Bible bids us return good for evil.",
    "As I took another breath, I saw the three stars again. They were not calling to me; they were letting me go, leaving me to the black universe I had wandered for so many lifetimes. I drifted into the black, and it got brighter and brighter. It wasn't black at all—it was blue. Warm, vibrant, brilliant blue... I floated into it with no fear at all.",
    "Religion is like language or dress. We gravitate toward the practices with which we were raised. In the end, though, we are all proclaiming the same thing. That life has meaning. That we are grateful for the power that created us.",
    "First, let no one rule your mind or body. Take special care that your thoughts remain unfettered... Give men your ear, but not your heart. Show respect for those in power, but don't follow them blindly. Judge with logic and reason, but comment not. Consider none your superior whatever their rank or station in life. Treat all fairly, or they will seek revenge. Be careful with your money. Hold fast to your beliefs and others will listen.",
    "Love, whether newly born or aroused from a deathlike slumber, must always create sunshine, filling the heart so full of radiance, that it overflows upon the outward world.",
    "You're both the fire and the water that extinguishes it. You're the narrator, the protagonist, and the sidekick. You're the storyteller and the story told. You are somebody's something, but you are also your you.",
    "When you cannot pinpoint a pain in your body, the whole world seems to throb with it. Trees in pain, lit windows in pain, Wednesday nights in pain. Pianos flaming with pain, and the scale sliding up into a cry.",
    "At an early age, I learned that people make mistakes, and you have to decide if their mistakes are bigger than your love for them.",
    "Grief was what you owed the dead for the necessary crime of living on without them.",
    "If you are one of those people who has the ability to make it down to the bottom of the ocean, the ability to swim the dark waters without fear, the astonishing ability to move through life's worst crucibles and not die, then you also have the ability to bring something back to the surface that helps others in a way that they cannot achieve themselves.",
    "Her life is architected, elegant and angular, a beauty to behold, and mine is a stew, a juicy, sloppy mess of ingredients and feelings and emotions, too much salt and spice, too much anxiety, always a little dribbling down the front of my shirt. But have you tasted it? It's delicious.",
    "I kept thinking about the uneven quality of time — the way it was almost always so empty, and then with no warning came a few days that felt so dense and alive and real that it seemed indisputable that that was what life was, that its real nature had finally been revealed.",
    "Mother died today. Or maybe yesterday, I don't know. I had a telegram from the home: ‘Mother passed away. Funeral tomorrow. Yours sincerely.' That doesn't mean anything. It may have been yesterday.",
    "America was never innocent. We popped our cherry on the boat over and looked back with no regrets. You can't ascribe our fall from grace to any single event or set of circumstances. You can't lose what you lacked at conception.",
    "The studio was filled with the rich odour of roses, and when the light summer wind stirred amidst the trees of the garden, there came through the open door the heavy scent of the lilac, or the more delicate perfume of the pink-flowering thorn.",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.",
    "I was 37 then, strapped in my seat as the huge 747 plunged through dense cloud cover on approach to Hamburg Airport. Cold November rains drenched the earth. lending everything the gloomy air of a Flemish landscape: the ground crew in waterproofs, a flag atop a squat building, a BMW billboard. So - Germany again.",
    "Nikki, the name we finally gave my younger daughter, is not an abbreviation; it was a compromise I reached with her father. For paradoxically it was he who wanted to give her a Japanese name and I – perhaps out of some selfish desire not to be reminded of the past – insisted on an English one.",
    "Her first name was India – she was never able to get used to it. It seemed to her that her parents must have been thinking of someone else when they named her. Or were they hoping for another sort of daughter? As a child she was often on the point of inquiring, but time passed, and she never did.",
    "For seven years I tried not to remember too much because there was too much to remember, and I didn't want to fall any further behind with the events of my life. I still don't have a vegetable garden. I still haven't been to France. I have gone to bed with enough people that they seem like actual people now, but while I was going to bed with them I thought I was catching up. I am sorry. I had lost what seemed like a lot of time.",
    "Nobody died that year. Nobody prospered. There were no births or marriages. Seventeen reverent satires were written – disrupting a cliche and, presumably, creating a genre. There was a dream, of course, but many of the most important things, I find, are the ones learned in your sleep. Speech, tennis, music, skiing, manners, love – you try them waking and perhaps balk at the jump, and then you're over.",
    "You don't know about me, without you have read a book by the name of The Adventures of Tom Sawyer, but that ain't no matter. That book was made by Mr Mark Twain, and he told the truth, mainly. There was things he stretched, but mainly he told the truth. That is nothing.",
    "It's funny. Don't ever tell anybody anything. If you do, you start missing everybody.",
    "He was soon borne away by the waves, and lost in darkness and distance.",
    "So we beat on, boats against the current, borne back ceaselessly into the past.",
    "There was a white horse, on a quiet winter morning when snow covered the streets gently and was not deep, and the sky was swept with vibrant stars, except in the east, where dawn was beginning in a light blue flood. The air was motionless, but would soon start to move as the sun came up and winds from Canada came charging down the Hudson.",
    "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.",
    "Stuff your eyes with wonder, he said, live as if you'd drop dead in ten seconds. See the world. It's more fantastic than any dream made or paid for in factories.",
    "You can tell yourself that you would be willing to lose everything you have in order to get something you want. But it’s a catch-22: all of those things you’re willing to lose are what make you recognizable. Lose them, and you’ve lost yourself.",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. You're on your own. And you know what you know. And YOU are the one who’ll decide where to go…",
    "I had forgotten that time wasn’t fixed like concrete but in fact was fluid as sand, or water. I had forgotten that even misery can end.",
    "If you want to know what a man’s like, take a good look at how he treats his inferiors, not his equals.",
    "We are the music-makers, And we are the dreamers of dreams, Wandering by lone sea-breakers, And sitting by desolate streams. World-losers and world-forsakers, Upon whom the pale moon gleams; Yet we are the movers and shakers, Of the world forever, it seems.",
    "The wide world is all about you: you can fence yourselves in, but you cannot for ever fence it out.",
    "There are many Beths in the world, shy and quiet, sitting in corners till needed, and living for others so cheerfully that no one sees the sacrifices till the little cricket on the hearth stops chirping, and the sweet, sunshiny presence vanishes, leaving silence and shadow behind.",
    "But of course we can’t take any credit for our talents. It’s how we use them that counts.",
    "The rules of the Hunger Games are simple. In punishment for the uprising, each of the twelve districts must provide one girl and one boy, called tributes, to participate. The twenty-four tributes will be imprisoned in a vast outdoor arena that could hold anything from a burning desert to a frozen wasteland. Over a period of several weeks, the competitors must fight to the death. The last tribute standing wins.",
    "It does not do to dwell on dreams and forget to live, remember that. Now, why don’t you put that admirable Cloak back on and get off to bed?",
    "Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?",
]

_translate = {
    "Common Phrases": COMMON_PHRASES,
    "Famous Novel Excerpts": NOVEL_EXCERPTS,
}
